### ISSUE TITLE
1.1.5 shasum fails on macos executor

### ISSUE THREAD

**Issue by ahampe** [codecov/codecov-circleci-orb#83]
Excerpt of our circle config:
```
version: 2.1

orbs:
  codecov: codecov/codecov@1.1.5

executors:
  env_executor:
    macos:
      xcode: "12.0.0"
```

Pipeline fails at "Validate codecov bash uploader" step:
```
#!/bin/bash --login -eo pipefail
VERSION=$(grep 'VERSION=\"[0-9\.]*\"' codecov | cut -d'"' -f2);
for i in 1 256 512
do
  shasum -a $i -c --ignore-missing <(curl -s https://raw.githubusercontent.com/codecov/codecov-bash/${VERSION}/SHA${i}SUM) ||
  shasum -a $i -c <(curl -s https://raw.githubusercontent.com/codecov/codecov-bash/${VERSION}/SHA${i}SUM)
done

Unknown option: ignore-missing
Type shasum -h for help
(23) Failed writing body
codecov: OK
shasum: env: 
env: FAILED open or read
shasum: WARNING: 1 listed file could not be read

Exited with code exit status 1
CircleCI received exit code 1
```

**Comment by thomasrockhu** [comment]
Thanks @ahampe, I'll be releasing 1.1.6 tomorrow which should fix this issue

**Comment by thomasrockhu** [comment]
@ahampe `1.1.6` was released, are you still experiencing the issue?

**Comment by thomasrockhu** [comment]
Apologies there was a bug in `1.1.6`, you should be able to use `1.2.0`

**Comment by kevinold** [comment]
@thomasrockhu We are still seeing this issue after an upgrade to `1.2.0` -- See this PR where renovate bot uses `1.2.0` https://github.com/cypress-io/cypress-realworld-app/pull/916

**Comment by thomasrockhu** [comment]
@kevinold I released `1.2.1` that should work on Windows now

**Comment by kevinold** [comment]
@thomasrockhu Unfortunately this failed with a similar issue when I upgraded to 1.2.1
https://github.com/cypress-io/cypress-realworld-app/pull/956

![Screen Shot 2021-05-25 at 2 40 04 PM](https://user-images.githubusercontent.com/21967/119558609-38f82600-bd67-11eb-9aaa-bff57ecf253b.png)

**Comment by thomasrockhu** [comment]
@kevinold I opened a PR [here](https://github.com/cypress-io/cypress-realworld-app/pull/958). I forgot to mention the `using_windows` parameter
